name: globtorch
description: Globtorch Android Application


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  gradient_app_bar: ^0.1.2
  animated_text_kit: ^2.2.0
  paynow: ^1.0.1
  argon_buttons_flutter: ^1.0.5
  shared_preferences: ^0.5.4
  flutter_downloader: ^1.3.4
  path_provider: ^1.4.0
  permission_handler: ^5.0.0
  dio: ^3.0.9
  flutter_pdf_viewer: ^0.6.1
  flutter_pdfview: ^1.0.3+5
  flutter_plugin_pdf_viewer: ^1.0.7
  flutter_html: ^0.11.1
  file_picker: ^2.0.7
  shimmer: ^1.1.0
  simple_animations: ^1.3.7
  curved_navigation_bar: ^0.3.2
  link: ^1.0.0
  workmanager: ^0.2.0
  flutter_local_notifications: ^3.0.1
  google_fonts: ^1.1.1
  flutter_rating_bar: ^3.2.0+1
  smooth_star_rating: 1.1.1
  intl: ^0.16.1
  connectivity: ^2.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/globt.jpg
    - assets/images/course.png
    - assets/images/launch.png
    - assets/images/splash.png

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pacifico-Regular.ttf 
