class Course {
  final String id;
  final String coursename;
  final String courselevel;
  final String courseprice;
  final String coursesubject1;
  final String coursesubject1chapter1;
  final String coursesub1chapter1content;
  final String coursesubject1chapter2;
  final String coursesubject1chapter3;
  final String coursesubject1chapter4;
  final String coursesubject1chapter5;
  final String coursesubject1chapter6;
  final String coursesubject1chapter7;
  final String coursesubject1chapter8;
  final String coursesubject1chapter9;
  final String coursesubject1chapter10;
  final String coursesubject1chapter11;
  final String coursesubject1chapter12;
  final String coursesubject1test;

  final String coursesubject2;
  final String coursesubject3;
  final String coursesubject4;
  final String coursesubject5;
  final String coursesubject6;
  final String coursesubject7;
  final String coursesubject8;

  final String image;

  const Course(
      {this.id,
      this.coursename,
      this.courselevel,
      this.courseprice,
      this.coursesubject1,
      this.coursesubject1chapter1,
      this.coursesub1chapter1content,
      this.coursesubject1chapter2,
      this.coursesubject1chapter3,
      this.coursesubject1chapter4,
      this.coursesubject1chapter5,
      this.coursesubject1chapter6,
      this.coursesubject1chapter7,
      this.coursesubject1chapter8,
      this.coursesubject1chapter9,
      this.coursesubject1chapter10,
      this.coursesubject1chapter11,
      this.coursesubject1chapter12,
      this.coursesubject1test,
      this.coursesubject2,
      this.coursesubject3,
      this.coursesubject4,
      this.coursesubject5,
      this.coursesubject6,
      this.coursesubject7,
      this.coursesubject8,
      this.image});
}

List<Course> courses = [
  const Course(
    id: "1",
    coursename: "Transport And Logistics Management Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months ",
    coursesubject1: "Management 1:",
    coursesubject1chapter1: "School of Management Thought",
    coursesubject1chapter3: "The Environment of a Business",
    coursesubject1chapter4: "Planning",
    coursesubject1chapter5: "Organising",
    coursesubject1chapter6: "Decision Making",
    coursesubject1chapter7: "Leading",
    coursesubject1chapter8: "Motivating",
    coursesubject1chapter9: "Communication",
    coursesubject1chapter10: "Control",
    coursesubject1chapter11: "Human Resource",
    coursesubject1chapter12: "Managing Change",
    coursesubject1test: "Test",
    coursesubject2: "Communication",
    coursesubject3: "Financial Accounting 1",
    coursesubject4: "Principles Of Law",
    coursesubject5: "Economics",
    coursesubject6: "Principles Of Logistics And Transport Management",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "2",
    coursename: "Financial Accounting Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Communication",
    coursesubject2: "Management 1",
    coursesubject3: "Economics",
    coursesubject4: "Principles Of Law",
    coursesubject5: "Financial Accounting 1",
    coursesubject6: "Cost & Management Accounting 1",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "3",
    coursename: "Office Administration Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Communication",
    coursesubject2: "Management 1",
    coursesubject3: "Secretarial Office Techniques",
    coursesubject4: "Public Relations",
    coursesubject5: "Typing Technology",
    coursesubject6: "Financial Accounting 1",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "4",
    coursename: "Human Resource Management Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Communication",
    coursesubject2: "Management 1",
    coursesubject3: "Economics",
    coursesubject4: "Principles Of Law",
    coursesubject5: "Financial Accounting 1",
    coursesubject6: "Human Resource Management 1",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "5",
    coursename: "Purchasing And Material Management Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Communication",
    coursesubject2: "Management 1",
    coursesubject3: "Economics",
    coursesubject4: "Principles Of Law",
    coursesubject5: "Financial Accounting 1",
    coursesubject6: "Purchasing & Materials Management 1",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "6",
    coursename: "Corporate Management Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Communication",
    coursesubject2: "Management 1",
    coursesubject3: "Economics",
    coursesubject4: "Principles Of Law",
    coursesubject5: "Financial Accounting 1",
    coursesubject6: "Administrative Practice",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "7",
    coursename: "Public Relations Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Communication",
    coursesubject2: "Management 1",
    coursesubject3: "Economics",
    coursesubject4: "Principles Of Law",
    coursesubject5: "Financial Accounting 1",
    coursesubject6: "Public Relations 1",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "8",
    coursename: "Cost Management Accounting Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Communication",
    coursesubject2: "Management 1",
    coursesubject3: "Economics",
    coursesubject4: "Principles Of Law",
    coursesubject5: "Financial Accounting 1",
    coursesubject6: "Cost & Management",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "9",
    coursename: "Marketing Management Certificate (IAC)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Communication",
    coursesubject2: "Management 1",
    coursesubject3: "Economics",
    coursesubject4: "Principles Of Law",
    coursesubject5: "Financial Accounting 1",
    coursesubject6: "Marketing Management 1",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "10",
    coursename: "Form 1 (ZIMSEC)",
    courselevel: "(Secondary)",
    courseprice: "Price:100RTGS/Year",
    coursesubject1: "Maths",
    coursesubject2: "English Language",
    coursesubject3: "Combined Science",
    coursesubject4: "Family & Rel Studies",
    coursesubject5: "Geography",
    coursesubject6: "History",
    coursesubject7: "Commerce",
    coursesubject8: "Agriculture",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "11",
    coursename: "Form 2 (ZIMSEC)",
    courselevel: "(Secondary)",
    courseprice: "Price:100RTGS/year",
    coursesubject1: "Maths",
    coursesubject2: "English Language",
    coursesubject3: "Combined Science",
    coursesubject4: "Family & Rel Studies",
    coursesubject5: "Geography",
    coursesubject6: "History",
    coursesubject7: "Commerce",
    coursesubject8: "Agriculture",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "12",
    coursename: "Form 3 (ZIMSEC)",
    courselevel: "(Secondary)",
    courseprice: "Price:100RTGS/yeara",
    coursesubject1: "Maths",
    coursesubject2: "English Language",
    coursesubject3: "Combined Science",
    coursesubject4: "Family & Rel Studies",
    coursesubject5: "Geography",
    coursesubject6: "History",
    coursesubject7: "Commerce",
    coursesubject8: "Agriculture",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "13",
    coursename: "Form 4 (ZIMSEC)",
    courselevel: "(Secondary)",
    courseprice: "Price:100RTGS/Year",
    coursesubject1: "Maths",
    coursesubject2: "English Language",
    coursesubject3: "Combined Science",
    coursesubject4: "Family & Rel Studies",
    coursesubject5: "Geography",
    coursesubject6: "History",
    coursesubject7: "Commerce",
    coursesubject8: "Agriculture",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "14",
    coursename: "Grade 7 (ZIMSEC)",
    courselevel: "(Primary)",
    courseprice: "Price:80RTGS/Year",
    coursesubject1: "Shona",
    coursesubject2: "Mathematics",
    coursesubject3: "English",
    coursesubject4: "General Paper",
    coursesubject5: "Agriculture",
    coursesubject6: "Family Religion And Moral Education",
    coursesubject7: "Science And Technology",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "15",
    coursename:
        "Introductory Certificate In Financial And Management Accounting (ACCA)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Recording Financial Transactions",
    coursesubject2: "Management Information",
    coursesubject3: "",
    coursesubject4: "",
    coursesubject5: "",
    coursesubject6: "",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "16",
    coursename: "Diploma In Accounting And Business (ACCA)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Accountant In Business",
    coursesubject2: "Management In Accounting",
    coursesubject3: "Financial Accounting",
    coursesubject4: "",
    coursesubject5: "",
    coursesubject6: "",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "17",
    coursename: "IGCSE CAMBRIDGE FORM 3 (IGCSE Cambridge O Level)",
    courselevel: "(Secondary)",
    courseprice: "Price:100RTGS/Year",
    coursesubject1: "IGCSE CAMBRIDGE ACCOUNTS",
    coursesubject2: "IGCSE CAMBRIDGE HISTORY",
    coursesubject3: "IGCSE CAMBRIDGE GEOGRAPHY",
    coursesubject4: "IGCSE CAMBRIDGE ENGLISH",
    coursesubject5: "IGCSE CAMBRIDGE BIOLOGY",
    coursesubject6: "",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "18",
    coursename: "IGCSE CAMBRIDGE FORM 4 (IGCSE Cambridge O Level)",
    courselevel: "(Secondary)",
    courseprice: "Price:100RTGS/Year",
    coursesubject1: "GEOGRAPHY",
    coursesubject2: "ACCOUNTING",
    coursesubject3: "",
    coursesubject4: "",
    coursesubject5: "",
    coursesubject6: "",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "19",
    coursename: "ICDL Digital Student (ICDL)",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "ICDL Computer Essentials",
    coursesubject2: "ICDL Online Essentials",
    coursesubject3: "ICDL Presentation 2013",
    coursesubject4: "ICDL Spreadsheets 2013",
    coursesubject5: "ICDL Using Databases 2013",
    coursesubject6: "ICDL Word Processing 2013",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
  const Course(
    id: "20",
    coursename: "ICDL Professionals- Marketing And Communications",
    courselevel: "(Tertiary)",
    courseprice: "Price:200RTGS/6 Months",
    coursesubject1: "Marketing And Communications",
    coursesubject2: "",
    coursesubject3: "",
    coursesubject4: "",
    coursesubject5: "",
    coursesubject6: "",
    coursesubject7: "",
    coursesubject8: "",
    image: "assets/images/course.png",
  ),
];
